apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openbalena.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  {{- if .Values.api.replicas }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          {{- if .Values.api.image.pullPolicy }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- end }}
          # XXX ports
          # TODO tmpfs (/run, /sys/fs/cgroup)
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "SYS_RESOURCE"]
          env:
          - name: CONFD_BACKEND
            value: "ENV"
          {{- with .Values.api.env }}  # XXX
            {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
