apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openbalena.s3.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbalena.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
spec:
  selector:
    matchLabels:
      {{- include "openbalena.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: s3
  serviceName: {{ include "openbalena.s3.fullname" . }}
  {{- if .Values.s3.podManagementPolicy }}
  podManagementPolicy: {{ .Values.s3.podManagementPolicy }}
  {{- end }}
  {{- if .Values.s3.replicas }}
  replicas: {{ .Values.s3.replicas }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "openbalena.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: s3
    spec:
      {{- if .Values.s3.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.s3.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-s3
        image: "{{ .Values.s3.image.repository }}:{{ .Values.s3.image.tag }}"
        # XXX ports
        volumeMounts:  # TODO tmpfs (/run, /sys/fs/cgroup)
        - name: {{ .Values.s3.name }}
          mountPath: /export
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_RESOURCE"]
        env:
        - name: CONFD_BACKEND
          value: "ENV"
        {{- with .Values.s3.env }}  # XXX
          {{- toYaml . | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.s3.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.s3.storageClassName }}
      storageClassName: {{ .Values.s3.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.s3.storage }}
